// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "charitato-20191120224414-hostingbucket-develop",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://charitato-20191120224414-hostingbucket-develop.s3-website.us-east-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:f435253a-d3fd-407f-a343-2ef3f0d5dd64",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tukSip755",
    "aws_user_pools_web_client_id": "360pbfv1isqi7ccdk98vmhs0tu",
    "oauth": {}
};


export default awsmobile;
